; 本文件由 scripts/update-langdata.ps1 从 Lang.ini 自动生成，请勿手工编辑。
; 修改 Lang.ini 后重新运行该脚本即可同步。

Global Const $g_sLangDataIniPart1 = _
"[en-US]" & @CRLF & _
"    LangTitle=English" & @CRLF & _
"    ChromePlusInstalledVersion=Installed:" & @CRLF & _
"    ChromePlusBundledVersion=Bundled:" & @CRLF & _
"    ChromePlusBundledHint=Bundled custom Chrome++ for Brave / Whale. Installed offline for the browser architecture." & @CRLF & _
"    InstallBundledChromePlus=Install bundled Chrome++" & @CRLF & _
"    ReplaceBundledChromePlus=Use bundled Chrome++" & @CRLF & _
"    ChromePlusBundledUnsupportedArch=Bundled Chrome++ supports only x86/x64. The browser architecture is unknown or unsupported." & @CRLF & _
"    ChromePlusBundledResourceFailed=The bundled Chrome++ DLL is missing, could not be extracted, or has an incorrect architecture." & @CRLF & _
"    InstallBundledChromePlusConfirm=The browser has been downloaded and extracted.\n\nChrome++ is optional and provides features such as right-clicking to close tabs and opening bookmarks in new tabs.\n\nInstall the bundled custom Chrome++? No download is required." & @CRLF & _
"    LangSupportAuthor=Ryan" & @CRLF & _
"    LangSupportUrl=https://doufu.ru" & @CRLF & _
"    UILanguage=Language" & @CRLF & _
"    RestartToApplyLanguage={AppName} will restart to apply new language!" & @CRLF & _
"    UpdateAvailable={AppName} {Version} already released，Release notes：\n\n\n{Notes}\nWould you like to update {AppName} to this version?" & @CRLF & _
"    CancelAppUpdate=Canceling update ..." & @CRLF & _
"    StartToDownloadApp=Starting to download {AppName}" & @CRLF & _
"    AppDownloadProgress=Downloading {AppName}\n%i KB already downloaded." & @CRLF & _
"    CancelAppUpdateConfirm=Downloading {AppName}, sure to cancel?" & @CRLF & _
"    ApplyingUpdate=Applying {AppName} update" & @CRLF & _
"    FailToDeCompressUpdateFile=Unpacking the update file failed." & @CRLF & _
"    FailToDownloadUpdateFile=Failed to download update file." & @CRLF & _
"    UpdateSuccessConfirm={AppName} has been updated to {Version}!\nOriginal{ScriptName} has been backuped to {ScriptNameBak}" & @CRLF & _
"    UpdateFailedConfirm=Automatic update RunFirefox failed: \n%s\n\nDo you go to the software release page and download RunFirefox manually?" & @CRLF & _
"    AppTitle={AppName} - Build your own portable browser" & @CRLF & _
"    AppCopyright={AppName} by Ryan <github-benzBrake@woai.ru>" & @CRLF & _
"    AppOriginalCopyright=Original Version By cnjackchen" & @CRLF & _
"    ClickToOpenPublishPage=Click to open the {AppName} release page" & @CRLF & _
"    ClickToOpenOriginalPage=Click to open the original myFirefox release page" & @CRLF & _
"    General=General" & @CRLF & _
"    RunFirefoxSettingsGroup=RunFirefox Settings" & @CRLF & _
"    BrowserFiles=Browser program files" & @CRLF & _
"    BrowserPath=Browser Path" & @CRLF & _
"    BrowserExecutablePath=Browser executable path" & @CRLF & _
"    Browse=Browse" & @CRLF & _
"    ChoosePortableBrowser=Select the portable browser executable" & @CRLF & _
"    BrowserType=Browser" & @CRLF & _
"    BrowserFirefox=Firefox" & @CRLF & _
"    BrowserZen=ZenBrowser" & @CRLF & _
"    BrowserFloorp=Floorp" & @CRLF & _
"    BrowserWaterfox=Waterfox" & @CRLF & _
"    BrowserLibreWolf=LibreWolf" & @CRLF & _
"    BrowserOtherFirefox=Other Firefox-based Browser" & @CRLF & _
"    BrowserChrome=Chrome" & @CRLF & _
"    BrowserTurbo=Turbo Browser" & @CRLF & _
"    BrowserHelium=Helium" & @CRLF & _
"    BrowserWhale=Naver Whale" & @CRLF & _
"    BrowserCent=Cent Browser" & @CRLF & _
"    BrowserVivaldi=Vivaldi" & @CRLF & _
"    BrowserOpera=Opera" & @CRLF & _
"    BrowserCocCoc=Cốc Cốc" & @CRLF & _
"    BrowserBrave=Brave" & @CRLF & _
"    BrowserXunlei=Xunlei Browser" & @CRLF & _
"    BrowserUngoogledChromium=Ungoogled Chromium" & @CRLF & _
"    BrowserOtherChromium=Other Chromium-based Browser" & @CRLF & _
"    UpdateChannel=Channel" & @CRLF & _
"    BrowserAutoUpdate=Auto update" & @CRLF & _
"    BrowserBitness=Browser bitness:" & @CRLF & _
"    CheckBrowserUpdate=Check browser updates:" & @CRLF & _
"    CheckBrowserUpdateOnStartup=On every startup" & @CRLF & _
"    CheckBrowserUpdateHourly=Every hour" & @CRLF & _
"    CheckBrowserUpdateDaily=Every day" & @CRLF & _
"    CheckBrowserUpdateWeekly=Every week" & @CRLF & _
"    CheckBrowserUpdateNever=Never" & @CRLF & _
"    LatestVersion=Latest version:" & @CRLF & _
"    CurrentVersion=Current version:" & @CRLF & _
"    BrowserDownloadAddress=Download address" & @CRLF & _
"    BrowserManagedDownloadUnavailable=Built-in download unavailable" & @CRLF & _
"    DownloadNow=Download now" & @CRLF & _
"    OpenDownloadPage=Open page" & @CRLF & _
"    BrowserVersionUnavailable=Failed" & @CRLF & _
"    BrowserVersionLoading=Loading version %s" & @CRLF & _
"    BrowserVersionLoadFailed=Failed to load browser version." & @CRLF & _
"    ProfileFiles=Browser profile files" & @CRLF & _
"    ProfileDirectory=Profile Directory" & @CRLF & _
"    ProfileDirectoryTooltip=Browser profile Directory" & @CRLF & _
"    ChooseProfileDirectory=Choose Profile Directory" & @CRLF & _
"    ExtractProfileFromSystem= Extract browser profile from the system" & @CRLF & _
"    NoticeMeWhenNewVersionPublished= Notify me of new {AppName} releases" & @CRLF & _
"    KeepRunFirefoxRunning= {AppName} runs in the background until the browser quits" & @CRLF & _
"    Advanced=Advanced" & @CRLF & _
"    NetworkTab=Network" & @CRLF & _
"    NetworkSettings=Network settings" & @CRLF & _
"    GithubApiMirror=GitHub API mirror:" & @CRLF & _
"    DownloadThreads=Download threads (1-10):" & @CRLF & _
"    ProxyType=Proxy type:" & @CRLF & _
"    ProxyTypeDirect=Direct connection" & @CRLF & _
"    ProxyTypeHttp=HTTP proxy" & @CRLF & _
"    ProxyTypeSocks5=SOCKS5 proxy" & @CRLF & _
"    ProxyServer=Proxy server:" & @CRLF & _
"    ProxyPort=Proxy port:" & @CRLF & _
"    CurlRequiredForThreads=Multi-threaded downloads require curl.exe. Only single-threaded downloads are used when curl is unavailable." & @CRLF & _
"    CurlRequiredForProxy=HTTP and SOCKS5 proxies require curl.exe. Install curl or select Direct connection." & @CRLF & _
"    ProxyServerRequired=A proxy server is required when a proxy is selected." & @CRLF & _
"    ProxyServerInvalid=The proxy server cannot contain whitespace or double quotes." & @CRLF & _
"    ProxyPortInvalid=The proxy port must be an integer from 1 to 65535." & @CRLF & _
"    DownloadingAppUpdate=Downloading RunFirefox update" & @CRLF & _
"    ChromePlusTab=Chrome++" & @CRLF & _
"    ChromePlusConfigFile=Config File" & @CRLF & _
"    ChromePlusTabsRequireChrome=Chrome++ tab settings are only available for Chromium-based browsers." & @CRLF & _
"    ChromePlusTabsUnsupportedBrowser=Chrome++ is not yet compatible with the current browser." & @CRLF & _
"    ChromePlusTabsPatchMissing=The current browser directory does not contain the Chrome++ patch (version.dll). Install it before editing these options." & @CRLF & _
"    ChromePlusTabsReady=Chrome++ was detected. The settings below will be written to chrome++.ini in the current browser directory." & @CRLF & _
"    DownloadChromePlusPatch=Download and install Chrome++" & @CRLF & _
"    UpdateChromePlusPatch=Update Chrome++" & @CRLF & _
"    ChromePlusDoubleClickClose=Double-click to close tab" & @CRLF & _
"    ChromePlusRightClickClose=Right-click to close tab" & @CRLF & _
"    ChromePlusKeepLastTab=Keep the last tab" & @CRLF & _
"    ChromePlusWheelTab=Switch tabs with the mouse wheel" & @CRLF & _
"    ChromePlusWheelTabWhenPressRButton=Switch tabs with the wheel while holding the right mouse button" & @CRLF & _
"    ChromePlusHoverTab=Activate a tab on hover" & @CRLF & _
"    ChromePlusHoverTabDelay=Delay (ms)" & @CRLF & _
"    ChromePlusHoverTabDelayTooltip=How long the cursor must rest on a tab before it activates. Range: 0-5000 ms; invalid values use 400 ms." & @CRLF & _
"    ChromePlusHoverTabVersionRequired=Hover activation requires Chrome++ 1.18.0 or later. Current version: %s" & @CRLF & _
"    ChromePlusOpenUrlNewTab=Open address bar input in a new tab" & @CRLF & _
"    ChromePlusOpenBookmarkNewTab=Open bookmarks in a new tab" & @CRLF & _
"    ChromePlusDisableNewTab=Disable the two options above on new tabs" & @CRLF & _
"    ChromePlusDisableNewTabName=Extra matched titles" & @CRLF & _
"    ChromePlusDisableNewTabNameTooltip=Raw value for chrome++.ini new_tab_disable_name. These titles are also treated as new tabs. You can enter multiple titles and keep the quotes and commas, for example ""about:blank"",""New Tab""" & @CRLF & _
"    ChromePlusNewTabDisableHelp=When checked, on a recognized new tab Chrome++ temporarily disables the two options above, so typed URLs and bookmarks reuse the current new tab.\n""Extra matched titles"" adds titles that are also treated as new tabs." & @CRLF

Global Const $g_sLangDataIniPart2 = _
"    ChromePlusSuppressFalseUpgradeNotification=Suppress the false ""out of date"" upgrade prompt" & @CRLF & _
"    ChromePlusSuppressFalseUpgradeNotificationHelp=Portable builds have no updater, so the browser shows an ""out of date / relaunch"" prompt that relaunching cannot clear. Only that false prompt is removed; genuine update notices are unaffected.\nWithout Chrome++, --disable-features=OutdatedBuildDetector is appended automatically at launch." & @CRLF & _
"    ChromePlusTabsSaveFailed=Failed to save Chrome++ tab settings:\n%s" & @CRLF & _
"    CacheSettings=Cache settings" & @CRLF & _
"    PluginsDirectory=Plugins Directory" & @CRLF & _
"    PluginsDirectoryTooltip=Browser plugins directory\nleave blank = default location" & @CRLF & _
"    SpecifyPluginsDirectory=Specify Plugins Directory" & @CRLF & _
"    SpecifyPluginsDirectoryTooltip=Select browser plugins directory" & @CRLF & _
"    CacheDirectory=Cache Directory" & @CRLF & _
"    CacheDirectoryTooltip=Browser cache location\nLeave blank = default location" & @CRLF & _
"    SpecifyCacheDirectory=Specify Cache Directory" & @CRLF & _
"    SpecifyCacheDirectoryTooltip=Select browser cache folder" & @CRLF & _
"    CacheSize=Cache Size" & @CRLF & _
"    CacheSizeTooltip=Cache size\nLeave blank = default size" & @CRLF & _
"    CacheSizeControl= Automatic cache size control" & @CRLF & _
"    ChromiumSettings=Chromium settings" & @CRLF & _
"    ImportGoogleApi=Import Google API" & @CRLF & _
"    ImportGoogleApiTooltip=Import Google API keys so Chromium can sign in to Google accounts" & @CRLF & _
"    SuppressGoogleApiWarning=Hide API warning" & @CRLF & _
"    SuppressGoogleApiWarningTooltip=Do not import Google API keys; only suppress the missing Google API key warning" & @CRLF & _
"    ClearGoogleApi=Clear Google API" & @CRLF & _
"    ClearGoogleApiTooltip=Without Google API keys, Chromium cannot sign in to Google accounts" & @CRLF & _
"    EnableChromiumDebugPort= Enable custom CDP debugging port" & @CRLF & _
"    ChromiumDebugPort=Port" & @CRLF & _
"    ChromiumDebugPortTooltip=CDP remote debugging port, from 1 to 65535." & @CRLF & _
"    ChromiumDebugPortConflictHelp=When enabled, a CDP argument is added automatically. Do not repeat a debugging port or pipe in the command line arguments below." & @CRLF & _
"    ChromiumDebugPortInvalid=The CDP debugging port must be an integer from 1 to 65535." & @CRLF & _
"    ChromiumDebugPortConflict=The custom CDP debugging port conflicts with a remote debugging argument in the command line parameters. Disable this setting or remove --remote-debugging-port / --remote-debugging-pipe from the command line parameters." & @CRLF & _
"    FirefoxSettings=Firefox settings" & @CRLF & _
"    EnableFirefoxDebugPort= Enable Firefox debug port" & @CRLF & _
"    FirefoxDebugPort=Port" & @CRLF & _
"    FirefoxDebugPortTooltip=Firefox Remote Agent (WebDriver BiDi) port, from 1 to 65535." & @CRLF & _
"    FirefoxDebugPortConflictHelp=When enabled, the Firefox Remote Agent port argument and --no-remote are added automatically. Do not repeat them in the command line arguments below." & @CRLF & _
"    FirefoxDebugPortInvalid=The Firefox remote debugging port must be an integer from 1 to 65535." & @CRLF & _
"    FirefoxDebugPortConflict=The Firefox remote debugging setting conflicts with the command line parameters. Disable this setting or remove --remote-debugging-port / --no-remote from the command line parameters." & @CRLF & _
"    GoogleApiImportSuccess=Google API keys imported successfully." & @CRLF & _
"    GoogleApiWarningSuppressSuccess=Google API key warning suppressed successfully." & @CRLF & _
"    GoogleApiClearSuccess=Google API keys cleared successfully." & @CRLF & _
"    GoogleApiEnvironmentUpdateFailed=Failed to update Google API environment variables." & @CRLF & _
"    GoogleApiUnavailable=This build does not include Google API keys. Configure GitHub Actions secrets and rebuild." & @CRLF & _
"    CommandLineArguments=Command Line Arguments" & @CRLF & _
"    CommandLineArgumentsTooltip=Browser command line parameters, write one parameter per line.\nsupports environment variables such as %TEMP%,\nin addition, %APP% represents the directory where RunFirefox is located" & @CRLF & _
"    Auxiliary=Utilities" & @CRLF & _
"    BossKeySettings=Bosskey" & @CRLF & _
"    EnableBossKey= Enable Bosskey" & @CRLF & _
"    BossKeyHotkey=Hotkey" & @CRLF & _
"    BossKeyHotkeyTooltip=Click here, then press a key combination. Press Backspace or Delete to clear it." & @CRLF & _
"    BossKeyHideToTray= Hide to system tray" & @CRLF & _
"    BossKeyDescription=Press the hotkey to hide the browser; press it again or click the tray icon to restore." & @CRLF & _
"    BossKeyTrayTooltip=Browser hidden. Click to restore." & @CRLF & _
"    RunOnBrowserStart=Run on browser startup" & @CRLF & _
"    AutoCloseAfterBrowserExit=# Auto-close after browser exit" & @CRLF & _
"    RunOnBrowserStartTooltip=External programs that run when the browser starts, support batch, vbs files, etc.\nIf you want to start parameters, you can add them after the program path" & @CRLF & _
"    Add=Add" & @CRLF & _
"    SelectExtraApp=Select Extra App" & @CRLF & _
"    RunAfterBrowserExit=Run after browser exit" & @CRLF & _
"    RunAfterBrowserExitTooltip=External programs that run after the browser exits, support batch, vbs files, etc.\nIf you want to start parameters, you can add them after the program path" & @CRLF & _
"    Confirm=Confirm" & @CRLF & _
"    ConfirmTooltip=Save the settings and start the browser" & @CRLF & _
"    Cancel=Cancel" & @CRLF & _
"    CancelTooltip=Do not save settings and exit" & @CRLF & _
"    Apply=Apply" & @CRLF & _
"    ApplyTooltip=Save settings" & @CRLF & _
"    DoublieClickToOpenSettingsWindow=Double-click the ""%s.vbs"" in the software directory to open this window" & @CRLF & _
"    ChooseExtraApp=Select the external programs to be run when the browser starts" & @CRLF & _
"    ExtraAppAllFiles=All files (*.*)" & @CRLF & _
"    ConfirmOverwriteBrowserFiles=The target directory already contains browser files or other files:\n%s\n\nContinue downloading and overwrite/merge files?" & @CRLF & _
"    BrowserDownloadFailed=Browser download or extraction failed:\n%s\n\nPlease check your network connection and target directory permissions, then try again." & @CRLF & _
"    BrowserDownloadSuccess=Browser has been downloaded and extracted." & @CRLF & _
"    BrowserAutoUpdateAvailable=A new browser version is available: %s\n\nDownload the update? It will be applied automatically the next time the browser starts." & @CRLF & _
"    BrowserUpdateStaged=The update package has been downloaded: %s\n\nIt will be applied automatically the next time the browser starts." & @CRLF & _
"    BrowserUpdateStageFailed=Failed to download the browser update package. It will be retried on the next update check." & @CRLF & _
"    BrowserUpdateStageFailedUrls=Download URLs attempted:\n%s" & @CRLF & _
"    BrowserUpdateProgressTitle=Applying browser update" & @CRLF & _
"    BrowserUpdateApplying=Applying update %s ..." & @CRLF & _
"    VerifyingBrowserUpdate=Verifying the update package, please wait ..." & @CRLF & _
"    BrowserUpdateApplyFailed=Failed to apply the browser update:\n%s" & @CRLF & _
"    OpenDownloadedBrowserConfirm=Browser has been downloaded and extracted.\nOpen it now?" & @CRLF & _
"    CannotCreateTempDirectory=Cannot create the temporary directory." & @CRLF & _
"    CannotCreateBrowserDirectory=Cannot create the browser target directory." & @CRLF & _
"    DownloadingBrowser=Downloading browser ..." & @CRLF & _
"    CannotStartBrowserDownload=Cannot start downloading browser." & @CRLF & _
"    BrowserDownloadProgressKnown=Downloaded {Downloaded} / {Total}" & @CRLF & _
"    BrowserDownloadProgressUnknown=Downloaded %s" & @CRLF & _
"    BrowserDownloadCancelled=Browser download was canceled." & @CRLF & _
"    InstallChromePlusPatchAfterDownloadConfirm=The browser has been downloaded and extracted.\n\nChrome++ is an optional patch; installation is not required. It provides features such as right-clicking to close tabs and opening bookmarks in new tabs.\n\nDownload and install the Chrome++ patch?" & @CRLF & _
"    PreparingChromePlusPatch=Preparing Chrome++ patch ..." & @CRLF & _
"    PreparingChromePlusPatchDetail=Loading the latest Chrome++ release information, please wait ..." & @CRLF & _
"    DownloadingChromePlusPatch=Downloading Chrome++ patch ..." & @CRLF & _
"    ChromePlusPatchInstallCancelled=Chrome++ patch download was canceled." & @CRLF & _
"    FailToGetChromePlusReleaseInfo=Failed to load Chrome++ release information." & @CRLF & _
"    FailToDownloadChromePlusPatch=Failed to download the Chrome++ patch." & @CRLF & _
"    FailToExtractChromePlusPatch=Failed to extract or install the Chrome++ patch." & @CRLF & _
"    ChromePlusPatchInstallFailed=Chrome++ patch installation failed." & @CRLF & _
"    ChromePlusPatchInstallFailedDetail=Chrome++ patch installation failed:\n%s" & @CRLF & _
"    ChromePlusPatchLogSaved=Diagnostic log was saved to:\n%s" & @CRLF & _
"    ViewLog=View log" & @CRLF & _
"    ChromePlusPatchInstalled=Chrome++ patch installed." & @CRLF & _
"    ChromePlusPatchProgressTitle=Preparing Chrome++ patch" & @CRLF & _
"    ExtractingChromePlusPatch=Installing Chrome++ patch, please wait ..." & @CRLF & _
"    ExtractingChromePlusPatchDetail=Please do not close {AppName} while the patch is being installed." & @CRLF & _
"    FailToDownloadBrowserInstaller=Failed to download the browser installer." & @CRLF & _
"    BrowserPackageHashMismatch=Browser package SHA-256 verification failed." & @CRLF & _
"    FailToExtractBrowserInstaller=Failed to extract the browser installer." & @CRLF & _
"    TriedDownloadUrls=Download URLs tried:" & @CRLF & _
"    BrowserInstallerSavePath=Installer save path:" & @CRLF & _
"    BrowserDownloadProgressTitle=Preparing browser" & @CRLF & _
"    ExtractingBrowser=Extracting browser, please wait ..." & @CRLF & _
"    ExtractingBrowserDetail=Please do not close {AppName} while extraction is running." & @CRLF & _
"    BrowserExtractLogKept=Diagnostic files were kept in:\n%s" & @CRLF & _
"    RunInBackgroundMessage=Allowing RunFirefox to run in the background can bring better user experience. If you cancel this option, please note the following points: \n\n 1. After locking the browser to the taskbar or setting it as the default browser, you need to run RunFirefox again to take effect; \n\n 2. The functions/options with ""#"" symbol in the RunFirefox settings screen will not be executed, including closing external programs, running external programs, etc. after the browser exits. \n\nAre you sure you want to remove this option?" & @CRLF & _
"    BrowserPathErrorMessage=Browser path is wrong, please reset it. \n\n%s" & @CRLF & _
"    PleaseProfileFolder=Please Set Profile Folder" & @CRLF & _
"    CannotExtratProfileFromSystem=The browser is running and cannot extract the configuration file! \nPlease close the browser and continue." & @CRLF & _
"    ExtractingProfile=The configuration file is being extracted, please wait ..." & @CRLF & _
"    ExtractProfileSuccess=Extracted profile successfully!" & @CRLF & _
"    ExtractProfileFailed=Extracted profile failed!" & @CRLF & _
"    ChooseBrowserExecutable=Choose browser executable(%s)" & @CRLF & _
"    ExecutableFile=Executable(*.exe)" & @CRLF & _
"    SpecifyProfileDirectory=Specify Profile Directory" & @CRLF

Global Const $g_sLangDataIniPart3 = _
"    JumpListFrequent=Frequent" & @CRLF & _
"    JumpListNewTab=New tab" & @CRLF & _
"    JumpListNewWindow=New window" & @CRLF & _
"    JumpListPrivateWindow=New private window" & @CRLF & _
"    JumpListLauncherSettings=Launcher settings" & @CRLF & _
"[zh-TW]" & @CRLF & _
"    ChromePlusInstalledVersion=已安裝版本：" & @CRLF & _
"    ChromePlusBundledVersion=內建版本：" & @CRLF & _
"    ChromePlusBundledHint=內建自行編譯版 Chrome++（Brave / Whale），依瀏覽器架構離線安裝。" & @CRLF & _
"    InstallBundledChromePlus=安裝內建 Chrome++" & @CRLF & _
"    ReplaceBundledChromePlus=替換為內建 Chrome++" & @CRLF & _
"    ChromePlusBundledUnsupportedArch=內建 Chrome++ 僅支援 x86/x64，無法辨識或不支援目前瀏覽器架構。" & @CRLF & _
"    ChromePlusBundledResourceFailed=內建 Chrome++ DLL 遺失、解壓縮失敗或架構不符。" & @CRLF & _
"    InstallBundledChromePlusConfirm=瀏覽器已下載並解壓縮完成。\n\nChrome++ 為選用補丁，可提供右鍵關閉分頁、書籤在新分頁開啟等功能。\n\n是否安裝內建自行編譯版 Chrome++？無需連線下載。" & @CRLF & _
"    LangTitle=繁體中文" & @CRLF & _
"    LangSupportAuthor=Ryan" & @CRLF & _
"    LangSupportUrl=https://doufu.ru" & @CRLF & _
"    UILanguage=顯示語言" & @CRLF & _
"    RestartToApplyLanguage=將重新啟動 {AppName} 以套用新語言！" & @CRLF & _
"    UpdateAvailable={AppName} {Version} 已發布，更新內容：\n\n\n{Notes}\n是否要自動更新到此版本？" & @CRLF & _
"    CancelAppUpdate=正在取消更新 ..." & @CRLF & _
"    StartToDownloadApp=開始下載 {AppName}" & @CRLF & _
"    AppDownloadProgress=正在下載 {AppName}\n已下載 %i KB。" & @CRLF & _
"    CancelAppUpdateConfirm=正在下載 {AppName}，確定要取消嗎？" & @CRLF & _
"    ApplyingUpdate=正在套用 {AppName} 更新" & @CRLF & _
"    FailToDeCompressUpdateFile=解壓縮更新檔案失敗。" & @CRLF & _
"    FailToDownloadUpdateFile=下載更新檔案失敗。" & @CRLF & _
"    UpdateSuccessConfirm={AppName} 已更新至 {Version}！\n原 {ScriptName} 已備份為 {ScriptNameBak}" & @CRLF & _
"    UpdateFailedConfirm={AppName} 自動更新失敗：\n%s\n\n是否前往軟體發布頁手動下載 {AppName}？" & @CRLF & _
"    AppTitle={AppName} - 打造自己的可攜瀏覽器" & @CRLF & _
"    AppCopyright={AppName} by Ryan <github-benzBrake@woai.ru>" & @CRLF & _
"    AppOriginalCopyright=原版 by 甲殼蟲" & @CRLF & _
"    ClickToOpenPublishPage=點擊開啟 {AppName} 發布頁" & @CRLF & _
"    ClickToOpenOriginalPage=點擊開啟甲殼蟲原版頁面" & @CRLF & _
"    General=一般" & @CRLF & _
"    RunFirefoxSettingsGroup=RunFirefox 設定" & @CRLF & _
"    BrowserFiles=瀏覽器程式檔案" & @CRLF & _
"    BrowserPath=瀏覽器路徑" & @CRLF & _
"    BrowserExecutablePath=瀏覽器主程式路徑" & @CRLF & _
"    Browse=瀏覽" & @CRLF & _
"    ChoosePortableBrowser=選擇可攜版瀏覽器主程式" & @CRLF & _
"    BrowserType=Browser" & @CRLF & _
"    BrowserFirefox=Firefox" & @CRLF & _
"    BrowserZen=ZenBrowser" & @CRLF & _
"    BrowserFloorp=Floorp" & @CRLF & _
"    BrowserWaterfox=Waterfox" & @CRLF & _
"    BrowserLibreWolf=LibreWolf" & @CRLF & _
"    BrowserOtherFirefox=其他 Firefox 衍生版" & @CRLF & _
"    BrowserChrome=Chrome" & @CRLF & _
"    BrowserTurbo=渦輪瀏覽器" & @CRLF & _
"    BrowserHelium=Helium" & @CRLF & _
"    BrowserWhale=Naver Whale" & @CRLF & _
"    BrowserCent=百分瀏覽器" & @CRLF & _
"    BrowserVivaldi=Vivaldi" & @CRLF & _
"    BrowserOpera=Opera" & @CRLF & _
"    BrowserCocCoc=Cốc Cốc" & @CRLF & _
"    BrowserBrave=Brave" & @CRLF & _
"    BrowserXunlei=迅雷瀏覽器" & @CRLF & _
"    BrowserUngoogledChromium=Ungoogled Chromium" & @CRLF & _
"    BrowserOtherChromium=其他 Chromium 瀏覽器" & @CRLF & _
"    UpdateChannel=更新通道" & @CRLF & _
"    BrowserAutoUpdate= 自動更新" & @CRLF & _
"    BrowserBitness=瀏覽器位數：" & @CRLF & _
"    CheckBrowserUpdate=檢查瀏覽器更新：" & @CRLF & _
"    CheckBrowserUpdateOnStartup=每次啟動時" & @CRLF & _
"    CheckBrowserUpdateHourly=每小時" & @CRLF & _
"    CheckBrowserUpdateDaily=每天" & @CRLF & _
"    CheckBrowserUpdateWeekly=每週" & @CRLF & _
"    CheckBrowserUpdateNever=從不" & @CRLF & _
"    LatestVersion=最新版本：" & @CRLF & _
"    CurrentVersion=目前版本：" & @CRLF & _
"    BrowserDownloadAddress=下載地址" & @CRLF & _
"    BrowserManagedDownloadUnavailable=不提供內建下載" & @CRLF & _
"    DownloadNow=立即下載" & @CRLF & _
"    OpenDownloadPage=開啟下載頁面" & @CRLF & _
"    BrowserVersionUnavailable=取得失敗" & @CRLF & _
"    BrowserVersionLoading=正在讀取版本 %s" & @CRLF & _
"    BrowserVersionLoadFailed=讀取瀏覽器版本失敗。" & @CRLF & _
"    ProfileFiles=瀏覽器使用者資料檔案" & @CRLF & _
"    ProfileDirectory=設定檔資料夾" & @CRLF & _
"    ProfileDirectoryTooltip=瀏覽器設定檔資料夾" & @CRLF & _
"    ChooseProfileDirectory=指定瀏覽器設定檔資料夾" & @CRLF & _
"    ExtractProfileFromSystem= 從系統中提取瀏覽器設定檔" & @CRLF & _
"    NoticeMeWhenNewVersionPublished= {AppName} 發布新版本時通知我" & @CRLF & _
"    KeepRunFirefoxRunning= {AppName} 在背景執行直到瀏覽器結束" & @CRLF & _
"    Advanced=進階" & @CRLF & _
"    NetworkTab=網路" & @CRLF & _
"    NetworkSettings=網路設定" & @CRLF & _
"    GithubApiMirror=Github API 加速：" & @CRLF & _
"    DownloadThreads=下載執行緒數（1-10）：" & @CRLF & _
"    ProxyType=代理類型：" & @CRLF & _
"    ProxyTypeDirect=直接連線" & @CRLF & _
"    ProxyTypeHttp=HTTP 代理" & @CRLF & _
"    ProxyTypeSocks5=SOCKS5 代理" & @CRLF & _
"    ProxyServer=代理伺服器：" & @CRLF & _
"    ProxyPort=代理連接埠：" & @CRLF & _
"    CurlRequiredForThreads=多執行緒下載需要 curl.exe；未偵測到時固定使用單執行緒。" & @CRLF & _
"    CurlRequiredForProxy=HTTP 與 SOCKS5 代理需要 curl.exe。請安裝 curl，或改用直接連線。" & @CRLF & _
"    ProxyServerRequired=使用代理時必須填寫代理伺服器。" & @CRLF & _
"    ProxyServerInvalid=代理伺服器不能包含空白字元或雙引號。" & @CRLF & _
"    ProxyPortInvalid=代理連接埠必須是 1-65535 之間的整數。" & @CRLF & _
"    DownloadingAppUpdate=正在下載 RunFirefox 更新" & @CRLF & _
"    ChromePlusTab=Chrome++" & @CRLF & _
"    ChromePlusConfigFile=設定檔" & @CRLF & _
"    ChromePlusTabsRequireChrome=目前僅能在 Chrome 系瀏覽器下設定 Chrome++ 分頁選項。" & @CRLF & _
"    ChromePlusTabsUnsupportedBrowser=Chrome++ 暫未相容目前瀏覽器。" & @CRLF & _
"    ChromePlusTabsPatchMissing=目前瀏覽器目錄未偵測到 Chrome++ 補丁（version.dll），安裝後才能修改這些選項。" & @CRLF & _
"    ChromePlusTabsReady=已偵測到 Chrome++ 補丁，以下設定將寫入目前瀏覽器目錄中的 chrome++.ini。" & @CRLF & _
"    DownloadChromePlusPatch=下載並安裝 Chrome++" & @CRLF & _
"    UpdateChromePlusPatch=更新 Chrome++" & @CRLF & _
"    ChromePlusDoubleClickClose=雙擊關閉分頁" & @CRLF & _
"    ChromePlusRightClickClose=右鍵關閉分頁" & @CRLF & _
"    ChromePlusKeepLastTab=保留最後一個分頁" & @CRLF & _
"    ChromePlusWheelTab=用滑鼠滾輪切換分頁" & @CRLF & _
"    ChromePlusWheelTabWhenPressRButton=按住右鍵時以滾輪切換分頁" & @CRLF & _
"    ChromePlusHoverTab=滑鼠懸停時啟用分頁" & @CRLF & _
"    ChromePlusHoverTabDelay=延遲（毫秒）" & @CRLF & _
"    ChromePlusHoverTabDelayTooltip=滑鼠需要在分頁上停留多久才會啟用，範圍為 0-5000 毫秒；無效值會使用 400 毫秒。" & @CRLF & _
"    ChromePlusHoverTabVersionRequired=滑鼠懸停啟用分頁需要 Chrome++ 1.18.0 或更新版本。目前版本：%s" & @CRLF & _
"    ChromePlusOpenUrlNewTab=網址列輸入在新分頁開啟" & @CRLF

Global Const $g_sLangDataIniPart4 = _
"    ChromePlusOpenBookmarkNewTab=書籤在新分頁開啟" & @CRLF & _
"    ChromePlusDisableNewTab=新分頁時停用上兩項" & @CRLF & _
"    ChromePlusDisableNewTabName=額外匹配標題" & @CRLF & _
"    ChromePlusDisableNewTabNameTooltip=對應 chrome++.ini 的 new_tab_disable_name 原始值；這些標題會被額外視為新分頁。可填入多個標題，並保留英文雙引號與逗號，例如 ""about:blank"",""新建标签""" & @CRLF & _
"    ChromePlusNewTabDisableHelp=勾選後，如果目前分頁被識別為新分頁，Chrome++ 會暫時停用上面的「網址列輸入在新分頁開啟」與「書籤在新分頁開啟」。這樣在新分頁中輸入網址或開啟書籤時，會使用目前新分頁，而不會再額外開新分頁。\n「額外匹配標題」用於補充 Chrome++ 的內建識別清單，符合這些標題時也會按新分頁處理。" & @CRLF & _
"    ChromePlusSuppressFalseUpgradeNotification=抑制錯誤的「已過期」升級提示" & @CRLF & _
"    ChromePlusSuppressFalseUpgradeNotificationHelp=可攜版瀏覽器沒有更新元件，會被誤報無法透過重新啟動消除的「已過期 / 重新啟動」提示；僅移除該錯誤提示，不影響真實更新通知。\n未安裝 Chrome++ 的瀏覽器啟動時會自動附加 --disable-features=OutdatedBuildDetector 參數。" & @CRLF & _
"    ChromePlusTabsSaveFailed=儲存 Chrome++ 分頁設定失敗：\n%s" & @CRLF & _
"    CacheSettings=快取設定" & @CRLF & _
"    PluginsDirectory=外掛目錄" & @CRLF & _
"    PluginsDirectoryTooltip=瀏覽器外掛目錄\n留空 = 預設位置" & @CRLF & _
"    SpecifyPluginsDirectory=指定外掛目錄" & @CRLF & _
"    SpecifyPluginsDirectoryTooltip=選擇瀏覽器外掛目錄" & @CRLF & _
"    CacheDirectory=快取位置" & @CRLF & _
"    CacheDirectoryTooltip=瀏覽器快取位置\n留空 = 預設位置" & @CRLF & _
"    SpecifyCacheDirectory=指定快取目錄" & @CRLF & _
"    SpecifyCacheDirectoryTooltip=選擇瀏覽器快取資料夾" & @CRLF & _
"    CacheSize=快取大小" & @CRLF & _
"    CacheSizeTooltip=快取大小\n留空 = 預設大小" & @CRLF & _
"    CacheSizeControl= 自動控制快取大小" & @CRLF & _
"    ChromiumSettings=Chromium 設定" & @CRLF & _
"    ImportGoogleApi=匯入 Google API" & @CRLF & _
"    ImportGoogleApiTooltip=匯入 Google API 金鑰後，Chromium 才能登入 Google 帳號" & @CRLF & _
"    SuppressGoogleApiWarning=清除 Google API 提示" & @CRLF & _
"    SuppressGoogleApiWarningTooltip=不匯入 Google API 金鑰，只清除缺少 Google API 金鑰提示" & @CRLF & _
"    ClearGoogleApi=清除 Google API" & @CRLF & _
"    ClearGoogleApiTooltip=缺少 Google API 金鑰會導致 Chromium 無法登入 Google 帳號" & @CRLF & _
"    EnableChromiumDebugPort= 啟用自訂 CDP 偵錯連接埠" & @CRLF & _
"    ChromiumDebugPort=連接埠" & @CRLF & _
"    ChromiumDebugPortTooltip=CDP 遠端偵錯連接埠，範圍為 1-65535。" & @CRLF & _
"    ChromiumDebugPortConflictHelp=啟用後會自動加入 CDP 參數，請勿在下方命令列參數中重複設定偵錯連接埠或偵錯管道。" & @CRLF & _
"    ChromiumDebugPortInvalid=CDP 偵錯連接埠必須是 1-65535 之間的整數。" & @CRLF & _
"    ChromiumDebugPortConflict=自訂 CDP 偵錯連接埠設定與命令列參數中的遠端偵錯參數衝突。請關閉此設定，或從命令列參數中移除 --remote-debugging-port / --remote-debugging-pipe。" & @CRLF & _
"    FirefoxSettings=Firefox 設定" & @CRLF & _
"    EnableFirefoxDebugPort= 啟用 Firefox 遠端偵錯連接埠" & @CRLF & _
"    FirefoxDebugPort=連接埠" & @CRLF & _
"    FirefoxDebugPortTooltip=Firefox Remote Agent（WebDriver BiDi）連接埠，範圍為 1-65535。" & @CRLF & _
"    FirefoxDebugPortConflictHelp=啟用後會自動加入 Firefox Remote Agent 連接埠參數和 --no-remote，請勿在下方命令列參數中重複設定。" & @CRLF & _
"    FirefoxDebugPortInvalid=Firefox 遠端偵錯連接埠必須是 1-65535 之間的整數。" & @CRLF & _
"    FirefoxDebugPortConflict=Firefox 遠端偵錯設定與命令列參數衝突。請關閉此設定，或從命令列參數中移除 --remote-debugging-port / --no-remote。" & @CRLF & _
"    GoogleApiImportSuccess=匯入 Google API 金鑰成功" & @CRLF & _
"    GoogleApiWarningSuppressSuccess=清除 Google API 金鑰提示成功" & @CRLF & _
"    GoogleApiClearSuccess=清除 Google API 金鑰成功" & @CRLF & _
"    GoogleApiEnvironmentUpdateFailed=修改 Google API 環境變數失敗。" & @CRLF & _
"    GoogleApiUnavailable=此建置未內建 Google API 金鑰。請設定 GitHub Actions secrets 後重新建置。" & @CRLF & _
"    CommandLineArguments=命令列參數" & @CRLF & _
"    CommandLineArgumentsTooltip=瀏覽器命令列參數，每行填寫一個參數。\n支援 %TEMP% 等環境變數，\n另外，%APP% 代表 RunFirefox 所在目錄" & @CRLF & _
"    Auxiliary=輔助" & @CRLF & _
"    BossKeySettings=Bosskey" & @CRLF & _
"    EnableBossKey= 啟用 Bosskey" & @CRLF & _
"    BossKeyHotkey=快捷鍵" & @CRLF & _
"    BossKeyHotkeyTooltip=點擊後直接按組合鍵；Backspace 或 Delete 清空" & @CRLF & _
"    BossKeyHideToTray= 隱藏到系統匣" & @CRLF & _
"    BossKeyDescription=按快捷鍵隱藏瀏覽器；再次按快捷鍵或點擊系統匣圖示還原。" & @CRLF & _
"    BossKeyTrayTooltip=瀏覽器已隱藏，點擊還原" & @CRLF & _
"    RunOnBrowserStart=瀏覽器啟動時執行" & @CRLF & _
"    AutoCloseAfterBrowserExit= #瀏覽器結束後自動關閉" & @CRLF & _
"    RunOnBrowserStartTooltip=瀏覽器啟動時執行的外部程式，支援批次檔、vbs 檔案等\n如需啟動參數，可加在程式路徑之後" & @CRLF & _
"    Add=新增" & @CRLF & _
"    SelectExtraApp=選擇外部程式" & @CRLF & _
"    RunAfterBrowserExit=瀏覽器結束後執行" & @CRLF & _
"    RunAfterBrowserExitTooltip=瀏覽器結束後執行的外部程式，支援批次檔、vbs 檔案等\n如需啟動參數，可加在程式路徑之後" & @CRLF & _
"    Confirm=確定" & @CRLF & _
"    ConfirmTooltip=儲存設定並啟動瀏覽器" & @CRLF & _
"    Cancel=取消" & @CRLF & _
"    CancelTooltip=不儲存設定並結束" & @CRLF & _
"    Apply=套用" & @CRLF & _
"    ApplyTooltip=儲存設定" & @CRLF & _
"    DoublieClickToOpenSettingsWindow=雙擊軟體目錄下的 ""%s.vbs"" 檔案可開啟此視窗" & @CRLF & _
"    ChooseExtraApp=選擇瀏覽器啟動時要執行的外部程式" & @CRLF & _
"    ExtraAppAllFiles=所有檔案 (*.*)" & @CRLF & _
"    ConfirmOverwriteBrowserFiles=The target directory already contains browser files or other files:\n%s\n\nContinue downloading and overwrite/merge files?" & @CRLF & _
"    BrowserDownloadFailed=Browser download or extraction failed:\n%s\n\nPlease check your network connection and target directory permissions, then try again." & @CRLF & _
"    BrowserDownloadSuccess=Browser has been downloaded and extracted." & @CRLF & _
"    BrowserAutoUpdateAvailable=發現瀏覽器新版本：%s\n\n是否下載更新？下載完成後將在下次啟動瀏覽器時自動套用。" & @CRLF & _
"    BrowserUpdateStaged=更新包已下載完成：%s\n\n下次啟動瀏覽器時將自動套用更新。" & @CRLF & _
"    BrowserUpdateStageFailed=瀏覽器更新包下載失敗，下次檢查時將重試。" & @CRLF & _
"    BrowserUpdateStageFailedUrls=已嘗試的下載地址：\n%s" & @CRLF & _
"    BrowserUpdateProgressTitle=正在套用瀏覽器更新" & @CRLF & _
"    BrowserUpdateApplying=正在套用更新 %s ..." & @CRLF & _
"    VerifyingBrowserUpdate=正在校驗更新包，請稍候 ..." & @CRLF & _
"    BrowserUpdateApplyFailed=套用瀏覽器更新失敗：\n%s" & @CRLF & _
"    OpenDownloadedBrowserConfirm=瀏覽器已下載並解壓縮完成。\n是否馬上開啟瀏覽器？" & @CRLF & _
"    CannotCreateTempDirectory=無法建立臨時目錄。" & @CRLF & _
"    CannotCreateBrowserDirectory=Cannot create the browser target directory." & @CRLF & _
"    DownloadingBrowser=Downloading browser ..." & @CRLF & _
"    CannotStartBrowserDownload=Cannot start downloading browser." & @CRLF & _
"    BrowserDownloadProgressKnown=已下載 {Downloaded} / {Total}" & @CRLF & _
"    BrowserDownloadProgressUnknown=已下載 %s" & @CRLF & _
"    BrowserDownloadCancelled=Browser download was canceled." & @CRLF & _
"    InstallChromePlusPatchAfterDownloadConfirm=瀏覽器已下載並解壓縮完成。\n\nChrome++ 為選用補丁，非必須安裝。安裝後可提供右鍵關閉分頁、書籤在新分頁開啟等功能。\n\n是否下載並安裝 Chrome++ 補丁？" & @CRLF & _
"    PreparingChromePlusPatch=正在準備 Chrome++ 補丁 ..." & @CRLF & _
"    PreparingChromePlusPatchDetail=正在讀取最新 Chrome++ 發布資訊，請稍候 ..." & @CRLF & _
"    DownloadingChromePlusPatch=正在下載 Chrome++ 補丁 ..." & @CRLF & _
"    ChromePlusPatchInstallCancelled=已取消 Chrome++ 補丁下載。" & @CRLF & _
"    FailToGetChromePlusReleaseInfo=讀取 Chrome++ 發布資訊失敗。" & @CRLF & _
"    FailToDownloadChromePlusPatch=下載 Chrome++ 補丁失敗。" & @CRLF & _
"    FailToExtractChromePlusPatch=解壓縮或安裝 Chrome++ 補丁失敗。" & @CRLF & _
"    ChromePlusPatchInstallFailed=Chrome++ 補丁安裝失敗。" & @CRLF & _
"    ChromePlusPatchInstallFailedDetail=Chrome++ 補丁安裝失敗：\n%s" & @CRLF & _
"    ChromePlusPatchLogSaved=診斷日誌已儲存到：\n%s" & @CRLF & _
"    ViewLog=檢視日誌" & @CRLF & _
"    ChromePlusPatchInstalled=Chrome++ 補丁已安裝。" & @CRLF & _
"    ChromePlusPatchProgressTitle=正在準備 Chrome++ 補丁" & @CRLF & _
"    ExtractingChromePlusPatch=正在安裝 Chrome++ 補丁，請稍候 ..." & @CRLF & _
"    ExtractingChromePlusPatchDetail=安裝期間請不要關閉 {AppName}。" & @CRLF & _
"    FailToDownloadBrowserInstaller=Failed to download the browser installer." & @CRLF & _
"    BrowserPackageHashMismatch=瀏覽器壓縮包 SHA-256 驗證失敗。" & @CRLF & _
"    FailToExtractBrowserInstaller=Failed to extract the browser installer." & @CRLF & _
"    TriedDownloadUrls=嘗試下載位址：" & @CRLF & _
"    BrowserInstallerSavePath=安裝包儲存路徑：" & @CRLF & _
"    BrowserDownloadProgressTitle=Preparing browser" & @CRLF & _
"    ExtractingBrowser=Extracting browser, please wait ..." & @CRLF & _
"    ExtractingBrowserDetail=Please do not close {AppName} while extraction is running." & @CRLF & _
"    BrowserExtractLogKept=診斷檔案已保留在：\n%s" & @CRLF & _
"    RunInBackgroundMessage=允許 RunFirefox 在背景執行可以帶來更好的使用體驗。若取消此選項，請注意以下幾點：\n\n 1. 將瀏覽器釘選到工作列或設為預設瀏覽器後，需再執行一次 RunFirefox 才能生效；\n\n 2. RunFirefox 設定介面中帶「#」符號的功能/選項將不會執行，包括瀏覽器結束後關閉外部程式、執行外部程式等。\n\n確定要取消此選項嗎？" & @CRLF & _
"    BrowserPathErrorMessage=瀏覽器路徑錯誤，請重新設定。\n\n%s" & @CRLF & _
"    PleaseProfileFolder=請設定設定檔資料夾！" & @CRLF & _
"    CannotExtratProfileFromSystem=瀏覽器正在執行，無法提取設定檔！\n請關閉瀏覽器後繼續。" & @CRLF & _
"    ExtractingProfile=正在提取設定檔，請稍候 ..." & @CRLF

Global Const $g_sLangDataIniPart5 = _
"    ExtractProfileSuccess=提取設定檔成功！" & @CRLF & _
"    ExtractProfileFailed=提取設定檔失敗！" & @CRLF & _
"    ChooseBrowserExecutable=Choose browser executable(%s)" & @CRLF & _
"    ExecutableFile=可執行檔(*.exe)" & @CRLF & _
"    SpecifyProfileDirectory=指定瀏覽器設定檔資料夾" & @CRLF & _
"    JumpListFrequent=常用" & @CRLF & _
"    JumpListNewTab=新增分頁" & @CRLF & _
"    JumpListNewWindow=新增視窗" & @CRLF & _
"    JumpListPrivateWindow=新增隱私視窗" & @CRLF & _
"    JumpListLauncherSettings=啟動器設定"

Global Const $g_sLangDataIni = _
$g_sLangDataIniPart1 & _
$g_sLangDataIniPart2 & _
$g_sLangDataIniPart3 & _
$g_sLangDataIniPart4 & _
$g_sLangDataIniPart5
